-- Kiểm tra trước khi deploy (enum OrderStatus / PaymentStatus): 2 query dưới chỉ được trả về các giá trị
-- PENDING | COMPLETED | CANCELLED và UNPAID | PAID, giá trị khác sẽ làm lỗi khi đọc đơn.
-- SELECT DISTINCT order_status FROM food_emolite.orders;
-- SELECT DISTINCT payment_status FROM food_emolite.orders;

ALTER TABLE food_emolite.store_foods
    ADD COLUMN IF NOT EXISTS cost_price NUMERIC(18, 2) NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS food_emolite.inventory_transactions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ref_code         VARCHAR(100),
    store_ref_code   VARCHAR(100)   NOT NULL,
    store_food_id    BIGINT         NOT NULL,
    type             VARCHAR(50)    NOT NULL,
    quantity_change  INTEGER        NOT NULL,
    quantity_after   INTEGER        NOT NULL,
    unit_cost        NUMERIC(18, 2),
    order_id         BIGINT,
    reference_code   VARCHAR(100),
    note             VARCHAR(500),
    created_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    created_by       BIGINT,
    updated_by       BIGINT
);

CREATE INDEX IF NOT EXISTS ix_inventory_transactions_store_created
    ON food_emolite.inventory_transactions (store_ref_code, created_at DESC);

CREATE INDEX IF NOT EXISTS ix_inventory_transactions_food
    ON food_emolite.inventory_transactions (store_food_id, created_at DESC);

CREATE TABLE IF NOT EXISTS food_emolite.inventory_receipts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ref_code        VARCHAR(100),
    store_ref_code  VARCHAR(100)   NOT NULL,
    receipt_code    VARCHAR(50)    NOT NULL,
    supplier_name   VARCHAR(255),
    note            VARCHAR(500),
    total_quantity  INTEGER        NOT NULL DEFAULT 0,
    total_amount    NUMERIC(18, 2) NOT NULL DEFAULT 0,
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    created_by      BIGINT,
    updated_by      BIGINT
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_inventory_receipts_store_code
    ON food_emolite.inventory_receipts (store_ref_code, receipt_code);

CREATE TABLE IF NOT EXISTS food_emolite.inventory_receipt_items (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ref_code       VARCHAR(100),
    receipt_id     BIGINT         NOT NULL REFERENCES food_emolite.inventory_receipts (id),
    store_food_id  BIGINT         NOT NULL,
    quantity       INTEGER        NOT NULL,
    unit_cost      NUMERIC(18, 2) NOT NULL,
    total_cost     NUMERIC(18, 2) NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    created_by     BIGINT,
    updated_by     BIGINT
);

CREATE INDEX IF NOT EXISTS ix_inventory_receipt_items_receipt
    ON food_emolite.inventory_receipt_items (receipt_id);

CREATE TABLE IF NOT EXISTS food_emolite.inventory_stocktakes (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ref_code          VARCHAR(100),
    store_ref_code    VARCHAR(100)   NOT NULL,
    stocktake_code    VARCHAR(50)    NOT NULL,
    note              VARCHAR(500),
    total_items       INTEGER        NOT NULL DEFAULT 0,
    total_difference  INTEGER        NOT NULL DEFAULT 0,
    difference_value  NUMERIC(18, 2) NOT NULL DEFAULT 0,
    created_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    created_by        BIGINT,
    updated_by        BIGINT
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_inventory_stocktakes_store_code
    ON food_emolite.inventory_stocktakes (store_ref_code, stocktake_code);

CREATE TABLE IF NOT EXISTS food_emolite.inventory_stocktake_items (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ref_code         VARCHAR(100),
    stocktake_id     BIGINT         NOT NULL REFERENCES food_emolite.inventory_stocktakes (id),
    store_food_id    BIGINT         NOT NULL,
    system_quantity  INTEGER        NOT NULL,
    actual_quantity  INTEGER        NOT NULL,
    difference       INTEGER        NOT NULL,
    unit_cost        NUMERIC(18, 2) NOT NULL DEFAULT 0,
    note             VARCHAR(500),
    created_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    created_by       BIGINT,
    updated_by       BIGINT
);

CREATE INDEX IF NOT EXISTS ix_inventory_stocktake_items_stocktake
    ON food_emolite.inventory_stocktake_items (stocktake_id);
