-- Thông báo cho chủ cửa hàng (chuông trên topbar agent) — entity: FoodEmolite.Domain.Entities.StoreNotification
CREATE TABLE IF NOT EXISTS food_emolite.store_notifications (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ref_code        VARCHAR(100),
    store_ref_code  VARCHAR(100)   NOT NULL,
    type            VARCHAR(50)    NOT NULL DEFAULT 'NEW_ORDER',
    order_id        BIGINT,
    order_code      VARCHAR(100),
    customer_name   VARCHAR(255),
    total_amount    NUMERIC(18, 2),
    is_read         BOOLEAN        NOT NULL DEFAULT FALSE,
    read_at         TIMESTAMP WITHOUT TIME ZONE,
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    created_by      BIGINT,
    updated_by      BIGINT
);

-- Lấy danh sách mới nhất theo cửa hàng + đếm số chưa đọc
CREATE INDEX IF NOT EXISTS ix_store_notifications_store_created
    ON food_emolite.store_notifications (store_ref_code, created_at DESC);

CREATE INDEX IF NOT EXISTS ix_store_notifications_store_unread
    ON food_emolite.store_notifications (store_ref_code)
    WHERE is_read = FALSE;
