CREATE TABLE IF NOT EXISTS food_emolite.suppliers (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ref_code        VARCHAR(100),
    store_ref_code  VARCHAR(100)   NOT NULL,
    supplier_code   VARCHAR(50)    NOT NULL,
    supplier_name   VARCHAR(255)   NOT NULL,
    contact_name    VARCHAR(255),
    phone           VARCHAR(20),
    email           VARCHAR(255),
    address         VARCHAR(500),
    tax_code        VARCHAR(50),
    note            VARCHAR(500),
    is_active       BOOLEAN        NOT NULL DEFAULT TRUE,
    is_deleted      BOOLEAN        NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    created_by      BIGINT,
    updated_by      BIGINT
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_suppliers_store_code
    ON food_emolite.suppliers (store_ref_code, supplier_code);

ALTER TABLE food_emolite.inventory_receipts
    ADD COLUMN IF NOT EXISTS supplier_id BIGINT REFERENCES food_emolite.suppliers (id);

CREATE INDEX IF NOT EXISTS ix_inventory_receipts_supplier
    ON food_emolite.inventory_receipts (supplier_id, created_at DESC);
